name = "LatLongDF"
uuid = "5157b5c0-f51a-4393-9dd9-f3da0678fc25"
authors = ["Matt Heath"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
DataFrames = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
